project_id = "boulevard-club"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/confirm"]
enable_signup = false
minimum_password_length = 12

[auth.email]
enable_signup = false
enable_confirmations = true
